import PHASE from '../../enums/forecast/phase';

export default {
    [PHASE.day]: {
        200: 'thunderstorms-line',
        300: 'drizzle-line',
        500: 'showers-line',
        502: 'heavy-showers-line',
        503: 'heavy-showers-line',
        504: 'heavy-showers-line',
        511: 'snowy-line',
        600: 'snowy-line',
        700: 'cloudy-line',
        701: 'mist-line',
        711: 'haze-line',
        721: 'haze-line',
        731: 'haze-line',
        741: 'sun-foggy-line',
        751: 'haze-line',
        761: 'haze-line',
        781: 'tornado-line',
        800: 'sun-line',
        801: 'cloudy-line',
        802: 'cloudy-line',
        803: 'cloudy-line',
        804: 'cloudy-line'
    },
    [PHASE.night]: {
        200: 'thunderstorms-line',
        300: 'drizzle-line',
        500: 'showers-line',
        502: 'heavy-showers-line',
        503: 'heavy-showers-line',
        504: 'heavy-showers-line',
        511: 'snowy-line',
        600: 'snowy-line',
        700: 'moon-cloudy-line',
        701: 'mist-line',
        711: 'haze-line',
        721: 'haze-line',
        731: 'haze-line',
        741: 'moon-foggy-line',
        751: 'haze-line',
        761: 'haze-line',
        781: 'tornado-line',
        800: 'moon-clear-line',
        801: 'moon-cloudy-line',
        802: 'moon-cloudy-line',
        803: 'moon-cloudy-line',
        804: 'moon-cloudy-line',
    }
};