import PRECIS from './precis';

export default {
    [PRECIS.fine]: 'sun',
    [PRECIS.mostlyFine]: 'cloud-sun',
    [PRECIS.highCloud]: 'cloud',
    [PRECIS.partlyCloudy]: 'cloud-sun',
    [PRECIS.mostlyCloudy]: 'cloud',
    [PRECIS.cloudy]: 'cloud',
    [PRECIS.overcast]: 'cloud',
    [PRECIS.showerOrTwo]: 'cloud-sun-rain',
    [PRECIS.chanceShowerFine]: 'cloud-sun-rain',
    [PRECIS.chanceShowerCloud]: 'cloud-showers-heavy',
    [PRECIS.drizzle]: 'cloud-showers-heavy',
    [PRECIS.fewShowers]: 'cloud-sun-rain',
    [PRECIS.showersRain]: 'cloud-rain',
    [PRECIS.heavyShowersRain]: 'cloud-rain',
    [PRECIS.chanceThunderstormFine]: 'bolt',
    [PRECIS.chanceThunderstormCloud]: 'bolt',
    [PRECIS.chanceThunderstormShowers]: 'bolt',
    [PRECIS.thunderstorm]: 'bolt',
    [PRECIS.chanceSnowFine]: 'snowflake',
    [PRECIS.chanceSnowCloud]: 'snowflake',
    [PRECIS.snowAndRain]: 'snowflake',
    [PRECIS.lightSnow]: 'snowflake',
    [PRECIS.snow]: 'snowflake',
    [PRECIS.heavySnow]: 'snowflake',
    [PRECIS.wind]: 'wind',
    [PRECIS.frost]: 'snowflake',
    [PRECIS.fog]: 'smog',
    [PRECIS.hail]: 'bolt',
    [PRECIS.dust ]: 'smog'
};