import PRECIS from './precis';

export default {
    [PRECIS.fine]: 'clear',
    [PRECIS.mostlyFine]: 'partly-cloudy',
    [PRECIS.highCloud]: 'partly-cloudy',
    [PRECIS.partlyCloudy]: 'partly-cloudy',
    [PRECIS.mostlyCloudy]: 'partly-cloudy',
    [PRECIS.cloudy]: 'cloudy',
    [PRECIS.overcast]: 'cloudy',
    [PRECIS.showerOrTwo]: 'cloudy',
    [PRECIS.chanceShowerFine]: 'partly-cloudy',
    [PRECIS.chanceShowerCloud]: 'partly-cloudy',
    [PRECIS.drizzle]: 'cloudy',
    [PRECIS.fewShowers]: 'cloudy',
    [PRECIS.showersRain]: 'cloudy',
    [PRECIS.heavyShowersRain]: 'cloudy',
    [PRECIS.chanceThunderstormFine]: 'partly-cloudy',
    [PRECIS.chanceThunderstormCloud]: 'partly-cloudy',
    [PRECIS.chanceThunderstormShowers]: 'partly-cloudy',
    [PRECIS.thunderstorm]: 'cloudy',
    [PRECIS.chanceSnowFine]: 'clear',
    [PRECIS.chanceSnowCloud]: 'clear',
    [PRECIS.snowAndRain]: 'cloudy',
    [PRECIS.lightSnow]: 'clear',
    [PRECIS.snow]: 'clear',
    [PRECIS.heavySnow]: 'clear',
    [PRECIS.wind]: 'clear',
    [PRECIS.frost]: 'clear',
    [PRECIS.fog]: 'clear',
    [PRECIS.hail]: 'clear',
    [PRECIS.dust ]: 'smog'
};